; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:HTIT]
platform = espressif32
board = um_tinys3
framework = arduino
monitor_speed = 115200
board_upload.wait_for_upload_port = false
build_flags = -DMQTT_MAX_PACKET_SIZE=1024
lib_deps = 
	mikalhart/TinyGPSPlus@^1.1.0
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.3.0

[env:ArduinoOTA]
extends = env:HTIT
upload_protocol = espota
upload_port = 145.126.61.113
upload_flags = 
	--port=3232
	--host_port=3232
	--auth="123456"
